
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model LogEntry
 * One block of logged work. Times are minutes since local midnight (0–1440).
 */
export type LogEntry = Prisma.LogEntryModel
/**
 * Model SyncSchedule
 * Single row (id = 1): when the server uploads entries to N-PAX.
 */
export type SyncSchedule = Prisma.SyncScheduleModel
/**
 * Model SyncRun
 * 
 */
export type SyncRun = Prisma.SyncRunModel
/**
 * Model NpaxCredential
 * Single row (id = 1): the N-PAX login saved by Connect, so the server can log in
 * again after a restart. The password is AES-256-GCM encrypted, never stored plain.
 */
export type NpaxCredential = Prisma.NpaxCredentialModel
