
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more LogEntries
 * const logEntries = await prisma.logEntry.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model LogEntry
 * One block of logged work. Times are minutes since local midnight (0–1440).
 */
export type LogEntry = Prisma.LogEntryModel
/**
 * Model SyncSchedule
 * Single row (id = 1): when the server uploads entries to N-PAX.
 */
export type SyncSchedule = Prisma.SyncScheduleModel
/**
 * Model SyncRun
 * 
 */
export type SyncRun = Prisma.SyncRunModel
/**
 * Model NpaxCredential
 * Single row (id = 1): the N-PAX login saved by Connect, so the server can log in
 * again after a restart. The password is AES-256-GCM encrypted, never stored plain.
 */
export type NpaxCredential = Prisma.NpaxCredentialModel
