
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NpaxCredential` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model NpaxCredential
 * Single row (id = 1): the N-PAX login saved by Connect, so the server can log in
 * again after a restart. The password is AES-256-GCM encrypted, never stored plain.
 */
export type NpaxCredentialModel = runtime.Types.Result.DefaultSelection<Prisma.$NpaxCredentialPayload>

export type AggregateNpaxCredential = {
  _count: NpaxCredentialCountAggregateOutputType | null
  _avg: NpaxCredentialAvgAggregateOutputType | null
  _sum: NpaxCredentialSumAggregateOutputType | null
  _min: NpaxCredentialMinAggregateOutputType | null
  _max: NpaxCredentialMaxAggregateOutputType | null
}

export type NpaxCredentialAvgAggregateOutputType = {
  id: number | null
}

export type NpaxCredentialSumAggregateOutputType = {
  id: number | null
}

export type NpaxCredentialMinAggregateOutputType = {
  id: number | null
  userId: string | null
  passwordEncrypted: string | null
  updatedAt: Date | null
}

export type NpaxCredentialMaxAggregateOutputType = {
  id: number | null
  userId: string | null
  passwordEncrypted: string | null
  updatedAt: Date | null
}

export type NpaxCredentialCountAggregateOutputType = {
  id: number
  userId: number
  passwordEncrypted: number
  updatedAt: number
  _all: number
}


export type NpaxCredentialAvgAggregateInputType = {
  id?: true
}

export type NpaxCredentialSumAggregateInputType = {
  id?: true
}

export type NpaxCredentialMinAggregateInputType = {
  id?: true
  userId?: true
  passwordEncrypted?: true
  updatedAt?: true
}

export type NpaxCredentialMaxAggregateInputType = {
  id?: true
  userId?: true
  passwordEncrypted?: true
  updatedAt?: true
}

export type NpaxCredentialCountAggregateInputType = {
  id?: true
  userId?: true
  passwordEncrypted?: true
  updatedAt?: true
  _all?: true
}

export type NpaxCredentialAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NpaxCredential to aggregate.
   */
  where?: Prisma.NpaxCredentialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NpaxCredentials to fetch.
   */
  orderBy?: Prisma.NpaxCredentialOrderByWithRelationInput | Prisma.NpaxCredentialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NpaxCredentialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NpaxCredentials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NpaxCredentials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NpaxCredentials
  **/
  _count?: true | NpaxCredentialCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NpaxCredentialAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NpaxCredentialSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NpaxCredentialMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NpaxCredentialMaxAggregateInputType
}

export type GetNpaxCredentialAggregateType<T extends NpaxCredentialAggregateArgs> = {
      [P in keyof T & keyof AggregateNpaxCredential]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNpaxCredential[P]>
    : Prisma.GetScalarType<T[P], AggregateNpaxCredential[P]>
}




export type NpaxCredentialGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NpaxCredentialWhereInput
  orderBy?: Prisma.NpaxCredentialOrderByWithAggregationInput | Prisma.NpaxCredentialOrderByWithAggregationInput[]
  by: Prisma.NpaxCredentialScalarFieldEnum[] | Prisma.NpaxCredentialScalarFieldEnum
  having?: Prisma.NpaxCredentialScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NpaxCredentialCountAggregateInputType | true
  _avg?: NpaxCredentialAvgAggregateInputType
  _sum?: NpaxCredentialSumAggregateInputType
  _min?: NpaxCredentialMinAggregateInputType
  _max?: NpaxCredentialMaxAggregateInputType
}

export type NpaxCredentialGroupByOutputType = {
  id: number
  userId: string
  passwordEncrypted: string
  updatedAt: Date
  _count: NpaxCredentialCountAggregateOutputType | null
  _avg: NpaxCredentialAvgAggregateOutputType | null
  _sum: NpaxCredentialSumAggregateOutputType | null
  _min: NpaxCredentialMinAggregateOutputType | null
  _max: NpaxCredentialMaxAggregateOutputType | null
}

export type GetNpaxCredentialGroupByPayload<T extends NpaxCredentialGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NpaxCredentialGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NpaxCredentialGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NpaxCredentialGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NpaxCredentialGroupByOutputType[P]>
      }
    >
  >



export type NpaxCredentialWhereInput = {
  AND?: Prisma.NpaxCredentialWhereInput | Prisma.NpaxCredentialWhereInput[]
  OR?: Prisma.NpaxCredentialWhereInput[]
  NOT?: Prisma.NpaxCredentialWhereInput | Prisma.NpaxCredentialWhereInput[]
  id?: Prisma.IntFilter<"NpaxCredential"> | number
  userId?: Prisma.StringFilter<"NpaxCredential"> | string
  passwordEncrypted?: Prisma.StringFilter<"NpaxCredential"> | string
  updatedAt?: Prisma.DateTimeFilter<"NpaxCredential"> | Date | string
}

export type NpaxCredentialOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NpaxCredentialWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.NpaxCredentialWhereInput | Prisma.NpaxCredentialWhereInput[]
  OR?: Prisma.NpaxCredentialWhereInput[]
  NOT?: Prisma.NpaxCredentialWhereInput | Prisma.NpaxCredentialWhereInput[]
  userId?: Prisma.StringFilter<"NpaxCredential"> | string
  passwordEncrypted?: Prisma.StringFilter<"NpaxCredential"> | string
  updatedAt?: Prisma.DateTimeFilter<"NpaxCredential"> | Date | string
}, "id">

export type NpaxCredentialOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.NpaxCredentialCountOrderByAggregateInput
  _avg?: Prisma.NpaxCredentialAvgOrderByAggregateInput
  _max?: Prisma.NpaxCredentialMaxOrderByAggregateInput
  _min?: Prisma.NpaxCredentialMinOrderByAggregateInput
  _sum?: Prisma.NpaxCredentialSumOrderByAggregateInput
}

export type NpaxCredentialScalarWhereWithAggregatesInput = {
  AND?: Prisma.NpaxCredentialScalarWhereWithAggregatesInput | Prisma.NpaxCredentialScalarWhereWithAggregatesInput[]
  OR?: Prisma.NpaxCredentialScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NpaxCredentialScalarWhereWithAggregatesInput | Prisma.NpaxCredentialScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"NpaxCredential"> | number
  userId?: Prisma.StringWithAggregatesFilter<"NpaxCredential"> | string
  passwordEncrypted?: Prisma.StringWithAggregatesFilter<"NpaxCredential"> | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"NpaxCredential"> | Date | string
}

export type NpaxCredentialCreateInput = {
  id?: number
  userId: string
  passwordEncrypted: string
  updatedAt?: Date | string
}

export type NpaxCredentialUncheckedCreateInput = {
  id?: number
  userId: string
  passwordEncrypted: string
  updatedAt?: Date | string
}

export type NpaxCredentialUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NpaxCredentialUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NpaxCredentialCreateManyInput = {
  id?: number
  userId: string
  passwordEncrypted: string
  updatedAt?: Date | string
}

export type NpaxCredentialUpdateManyMutationInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NpaxCredentialUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NpaxCredentialCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NpaxCredentialAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type NpaxCredentialMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NpaxCredentialMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NpaxCredentialSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type NpaxCredentialSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  passwordEncrypted?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["npaxCredential"]>

export type NpaxCredentialSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  passwordEncrypted?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["npaxCredential"]>

export type NpaxCredentialSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  passwordEncrypted?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["npaxCredential"]>

export type NpaxCredentialSelectScalar = {
  id?: boolean
  userId?: boolean
  passwordEncrypted?: boolean
  updatedAt?: boolean
}

export type NpaxCredentialOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "passwordEncrypted" | "updatedAt", ExtArgs["result"]["npaxCredential"]>

export type $NpaxCredentialPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NpaxCredential"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    userId: string
    /**
     * "iv:authTag:ciphertext", base64 parts; see EncryptionService.
     */
    passwordEncrypted: string
    updatedAt: Date
  }, ExtArgs["result"]["npaxCredential"]>
  composites: {}
}

export type NpaxCredentialGetPayload<S extends boolean | null | undefined | NpaxCredentialDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload, S>

export type NpaxCredentialCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NpaxCredentialFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NpaxCredentialCountAggregateInputType | true
  }

export interface NpaxCredentialDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NpaxCredential'], meta: { name: 'NpaxCredential' } }
  /**
   * Find zero or one NpaxCredential that matches the filter.
   * @param {NpaxCredentialFindUniqueArgs} args - Arguments to find a NpaxCredential
   * @example
   * // Get one NpaxCredential
   * const npaxCredential = await prisma.npaxCredential.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NpaxCredentialFindUniqueArgs>(args: Prisma.SelectSubset<T, NpaxCredentialFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NpaxCredentialClient<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NpaxCredential that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NpaxCredentialFindUniqueOrThrowArgs} args - Arguments to find a NpaxCredential
   * @example
   * // Get one NpaxCredential
   * const npaxCredential = await prisma.npaxCredential.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NpaxCredentialFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NpaxCredentialFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NpaxCredentialClient<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NpaxCredential that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NpaxCredentialFindFirstArgs} args - Arguments to find a NpaxCredential
   * @example
   * // Get one NpaxCredential
   * const npaxCredential = await prisma.npaxCredential.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NpaxCredentialFindFirstArgs>(args?: Prisma.SelectSubset<T, NpaxCredentialFindFirstArgs<ExtArgs>>): Prisma.Prisma__NpaxCredentialClient<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NpaxCredential that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NpaxCredentialFindFirstOrThrowArgs} args - Arguments to find a NpaxCredential
   * @example
   * // Get one NpaxCredential
   * const npaxCredential = await prisma.npaxCredential.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NpaxCredentialFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NpaxCredentialFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NpaxCredentialClient<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NpaxCredentials that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NpaxCredentialFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NpaxCredentials
   * const npaxCredentials = await prisma.npaxCredential.findMany()
   * 
   * // Get first 10 NpaxCredentials
   * const npaxCredentials = await prisma.npaxCredential.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const npaxCredentialWithIdOnly = await prisma.npaxCredential.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NpaxCredentialFindManyArgs>(args?: Prisma.SelectSubset<T, NpaxCredentialFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NpaxCredential.
   * @param {NpaxCredentialCreateArgs} args - Arguments to create a NpaxCredential.
   * @example
   * // Create one NpaxCredential
   * const NpaxCredential = await prisma.npaxCredential.create({
   *   data: {
   *     // ... data to create a NpaxCredential
   *   }
   * })
   * 
   */
  create<T extends NpaxCredentialCreateArgs>(args: Prisma.SelectSubset<T, NpaxCredentialCreateArgs<ExtArgs>>): Prisma.Prisma__NpaxCredentialClient<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NpaxCredentials.
   * @param {NpaxCredentialCreateManyArgs} args - Arguments to create many NpaxCredentials.
   * @example
   * // Create many NpaxCredentials
   * const npaxCredential = await prisma.npaxCredential.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NpaxCredentialCreateManyArgs>(args?: Prisma.SelectSubset<T, NpaxCredentialCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NpaxCredentials and returns the data saved in the database.
   * @param {NpaxCredentialCreateManyAndReturnArgs} args - Arguments to create many NpaxCredentials.
   * @example
   * // Create many NpaxCredentials
   * const npaxCredential = await prisma.npaxCredential.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NpaxCredentials and only return the `id`
   * const npaxCredentialWithIdOnly = await prisma.npaxCredential.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NpaxCredentialCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NpaxCredentialCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NpaxCredential.
   * @param {NpaxCredentialDeleteArgs} args - Arguments to delete one NpaxCredential.
   * @example
   * // Delete one NpaxCredential
   * const NpaxCredential = await prisma.npaxCredential.delete({
   *   where: {
   *     // ... filter to delete one NpaxCredential
   *   }
   * })
   * 
   */
  delete<T extends NpaxCredentialDeleteArgs>(args: Prisma.SelectSubset<T, NpaxCredentialDeleteArgs<ExtArgs>>): Prisma.Prisma__NpaxCredentialClient<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NpaxCredential.
   * @param {NpaxCredentialUpdateArgs} args - Arguments to update one NpaxCredential.
   * @example
   * // Update one NpaxCredential
   * const npaxCredential = await prisma.npaxCredential.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NpaxCredentialUpdateArgs>(args: Prisma.SelectSubset<T, NpaxCredentialUpdateArgs<ExtArgs>>): Prisma.Prisma__NpaxCredentialClient<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NpaxCredentials.
   * @param {NpaxCredentialDeleteManyArgs} args - Arguments to filter NpaxCredentials to delete.
   * @example
   * // Delete a few NpaxCredentials
   * const { count } = await prisma.npaxCredential.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NpaxCredentialDeleteManyArgs>(args?: Prisma.SelectSubset<T, NpaxCredentialDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NpaxCredentials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NpaxCredentialUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NpaxCredentials
   * const npaxCredential = await prisma.npaxCredential.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NpaxCredentialUpdateManyArgs>(args: Prisma.SelectSubset<T, NpaxCredentialUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NpaxCredentials and returns the data updated in the database.
   * @param {NpaxCredentialUpdateManyAndReturnArgs} args - Arguments to update many NpaxCredentials.
   * @example
   * // Update many NpaxCredentials
   * const npaxCredential = await prisma.npaxCredential.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NpaxCredentials and only return the `id`
   * const npaxCredentialWithIdOnly = await prisma.npaxCredential.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NpaxCredentialUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NpaxCredentialUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NpaxCredential.
   * @param {NpaxCredentialUpsertArgs} args - Arguments to update or create a NpaxCredential.
   * @example
   * // Update or create a NpaxCredential
   * const npaxCredential = await prisma.npaxCredential.upsert({
   *   create: {
   *     // ... data to create a NpaxCredential
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NpaxCredential we want to update
   *   }
   * })
   */
  upsert<T extends NpaxCredentialUpsertArgs>(args: Prisma.SelectSubset<T, NpaxCredentialUpsertArgs<ExtArgs>>): Prisma.Prisma__NpaxCredentialClient<runtime.Types.Result.GetResult<Prisma.$NpaxCredentialPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NpaxCredentials.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NpaxCredentialCountArgs} args - Arguments to filter NpaxCredentials to count.
   * @example
   * // Count the number of NpaxCredentials
   * const count = await prisma.npaxCredential.count({
   *   where: {
   *     // ... the filter for the NpaxCredentials we want to count
   *   }
   * })
  **/
  count<T extends NpaxCredentialCountArgs>(
    args?: Prisma.Subset<T, NpaxCredentialCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NpaxCredentialCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NpaxCredential.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NpaxCredentialAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NpaxCredentialAggregateArgs>(args: Prisma.Subset<T, NpaxCredentialAggregateArgs>): Prisma.PrismaPromise<GetNpaxCredentialAggregateType<T>>

  /**
   * Group by NpaxCredential.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NpaxCredentialGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NpaxCredentialGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NpaxCredentialGroupByArgs['orderBy'] }
      : { orderBy?: NpaxCredentialGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NpaxCredentialGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNpaxCredentialGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NpaxCredential model
 */
readonly fields: NpaxCredentialFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NpaxCredential.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NpaxCredentialClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NpaxCredential model
 */
export interface NpaxCredentialFieldRefs {
  readonly id: Prisma.FieldRef<"NpaxCredential", 'Int'>
  readonly userId: Prisma.FieldRef<"NpaxCredential", 'String'>
  readonly passwordEncrypted: Prisma.FieldRef<"NpaxCredential", 'String'>
  readonly updatedAt: Prisma.FieldRef<"NpaxCredential", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NpaxCredential findUnique
 */
export type NpaxCredentialFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * Filter, which NpaxCredential to fetch.
   */
  where: Prisma.NpaxCredentialWhereUniqueInput
}

/**
 * NpaxCredential findUniqueOrThrow
 */
export type NpaxCredentialFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * Filter, which NpaxCredential to fetch.
   */
  where: Prisma.NpaxCredentialWhereUniqueInput
}

/**
 * NpaxCredential findFirst
 */
export type NpaxCredentialFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * Filter, which NpaxCredential to fetch.
   */
  where?: Prisma.NpaxCredentialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NpaxCredentials to fetch.
   */
  orderBy?: Prisma.NpaxCredentialOrderByWithRelationInput | Prisma.NpaxCredentialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NpaxCredentials.
   */
  cursor?: Prisma.NpaxCredentialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NpaxCredentials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NpaxCredentials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NpaxCredentials.
   */
  distinct?: Prisma.NpaxCredentialScalarFieldEnum | Prisma.NpaxCredentialScalarFieldEnum[]
}

/**
 * NpaxCredential findFirstOrThrow
 */
export type NpaxCredentialFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * Filter, which NpaxCredential to fetch.
   */
  where?: Prisma.NpaxCredentialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NpaxCredentials to fetch.
   */
  orderBy?: Prisma.NpaxCredentialOrderByWithRelationInput | Prisma.NpaxCredentialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NpaxCredentials.
   */
  cursor?: Prisma.NpaxCredentialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NpaxCredentials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NpaxCredentials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NpaxCredentials.
   */
  distinct?: Prisma.NpaxCredentialScalarFieldEnum | Prisma.NpaxCredentialScalarFieldEnum[]
}

/**
 * NpaxCredential findMany
 */
export type NpaxCredentialFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * Filter, which NpaxCredentials to fetch.
   */
  where?: Prisma.NpaxCredentialWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NpaxCredentials to fetch.
   */
  orderBy?: Prisma.NpaxCredentialOrderByWithRelationInput | Prisma.NpaxCredentialOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NpaxCredentials.
   */
  cursor?: Prisma.NpaxCredentialWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NpaxCredentials from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NpaxCredentials.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NpaxCredentials.
   */
  distinct?: Prisma.NpaxCredentialScalarFieldEnum | Prisma.NpaxCredentialScalarFieldEnum[]
}

/**
 * NpaxCredential create
 */
export type NpaxCredentialCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * The data needed to create a NpaxCredential.
   */
  data: Prisma.XOR<Prisma.NpaxCredentialCreateInput, Prisma.NpaxCredentialUncheckedCreateInput>
}

/**
 * NpaxCredential createMany
 */
export type NpaxCredentialCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NpaxCredentials.
   */
  data: Prisma.NpaxCredentialCreateManyInput | Prisma.NpaxCredentialCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NpaxCredential createManyAndReturn
 */
export type NpaxCredentialCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * The data used to create many NpaxCredentials.
   */
  data: Prisma.NpaxCredentialCreateManyInput | Prisma.NpaxCredentialCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NpaxCredential update
 */
export type NpaxCredentialUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * The data needed to update a NpaxCredential.
   */
  data: Prisma.XOR<Prisma.NpaxCredentialUpdateInput, Prisma.NpaxCredentialUncheckedUpdateInput>
  /**
   * Choose, which NpaxCredential to update.
   */
  where: Prisma.NpaxCredentialWhereUniqueInput
}

/**
 * NpaxCredential updateMany
 */
export type NpaxCredentialUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NpaxCredentials.
   */
  data: Prisma.XOR<Prisma.NpaxCredentialUpdateManyMutationInput, Prisma.NpaxCredentialUncheckedUpdateManyInput>
  /**
   * Filter which NpaxCredentials to update
   */
  where?: Prisma.NpaxCredentialWhereInput
  /**
   * Limit how many NpaxCredentials to update.
   */
  limit?: number
}

/**
 * NpaxCredential updateManyAndReturn
 */
export type NpaxCredentialUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * The data used to update NpaxCredentials.
   */
  data: Prisma.XOR<Prisma.NpaxCredentialUpdateManyMutationInput, Prisma.NpaxCredentialUncheckedUpdateManyInput>
  /**
   * Filter which NpaxCredentials to update
   */
  where?: Prisma.NpaxCredentialWhereInput
  /**
   * Limit how many NpaxCredentials to update.
   */
  limit?: number
}

/**
 * NpaxCredential upsert
 */
export type NpaxCredentialUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * The filter to search for the NpaxCredential to update in case it exists.
   */
  where: Prisma.NpaxCredentialWhereUniqueInput
  /**
   * In case the NpaxCredential found by the `where` argument doesn't exist, create a new NpaxCredential with this data.
   */
  create: Prisma.XOR<Prisma.NpaxCredentialCreateInput, Prisma.NpaxCredentialUncheckedCreateInput>
  /**
   * In case the NpaxCredential was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NpaxCredentialUpdateInput, Prisma.NpaxCredentialUncheckedUpdateInput>
}

/**
 * NpaxCredential delete
 */
export type NpaxCredentialDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
  /**
   * Filter which NpaxCredential to delete.
   */
  where: Prisma.NpaxCredentialWhereUniqueInput
}

/**
 * NpaxCredential deleteMany
 */
export type NpaxCredentialDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NpaxCredentials to delete
   */
  where?: Prisma.NpaxCredentialWhereInput
  /**
   * Limit how many NpaxCredentials to delete.
   */
  limit?: number
}

/**
 * NpaxCredential without action
 */
export type NpaxCredentialDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NpaxCredential
   */
  select?: Prisma.NpaxCredentialSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NpaxCredential
   */
  omit?: Prisma.NpaxCredentialOmit<ExtArgs> | null
}
