
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SyncSchedule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SyncSchedule
 * One row per user: when the server uploads that user's entries to N-PAX.
 */
export type SyncScheduleModel = runtime.Types.Result.DefaultSelection<Prisma.$SyncSchedulePayload>

export type AggregateSyncSchedule = {
  _count: SyncScheduleCountAggregateOutputType | null
  _avg: SyncScheduleAvgAggregateOutputType | null
  _sum: SyncScheduleSumAggregateOutputType | null
  _min: SyncScheduleMinAggregateOutputType | null
  _max: SyncScheduleMaxAggregateOutputType | null
}

export type SyncScheduleAvgAggregateOutputType = {
  dailyAtMinutes: number | null
  intervalHours: number | null
  windowStartMinutes: number | null
  windowEndMinutes: number | null
  days: number | null
  monthlyDaysBeforeEnd: number | null
  retryAttempts: number | null
}

export type SyncScheduleSumAggregateOutputType = {
  dailyAtMinutes: number | null
  intervalHours: number | null
  windowStartMinutes: number | null
  windowEndMinutes: number | null
  days: number[]
  monthlyDaysBeforeEnd: number | null
  retryAttempts: number | null
}

export type SyncScheduleMinAggregateOutputType = {
  userId: string | null
  enabled: boolean | null
  mode: string | null
  dailyAtMinutes: number | null
  intervalHours: number | null
  windowStartMinutes: number | null
  windowEndMinutes: number | null
  monthlyDaysBeforeEnd: number | null
  monthlyWeekdaysOnly: boolean | null
  targetUrl: string | null
  retryAttempts: number | null
  skipEmptyDays: boolean | null
  updatedAt: Date | null
}

export type SyncScheduleMaxAggregateOutputType = {
  userId: string | null
  enabled: boolean | null
  mode: string | null
  dailyAtMinutes: number | null
  intervalHours: number | null
  windowStartMinutes: number | null
  windowEndMinutes: number | null
  monthlyDaysBeforeEnd: number | null
  monthlyWeekdaysOnly: boolean | null
  targetUrl: string | null
  retryAttempts: number | null
  skipEmptyDays: boolean | null
  updatedAt: Date | null
}

export type SyncScheduleCountAggregateOutputType = {
  userId: number
  enabled: number
  mode: number
  dailyAtMinutes: number
  intervalHours: number
  windowStartMinutes: number
  windowEndMinutes: number
  days: number
  monthlyDaysBeforeEnd: number
  monthlyWeekdaysOnly: number
  targetUrl: number
  retryAttempts: number
  skipEmptyDays: number
  updatedAt: number
  _all: number
}


export type SyncScheduleAvgAggregateInputType = {
  dailyAtMinutes?: true
  intervalHours?: true
  windowStartMinutes?: true
  windowEndMinutes?: true
  days?: true
  monthlyDaysBeforeEnd?: true
  retryAttempts?: true
}

export type SyncScheduleSumAggregateInputType = {
  dailyAtMinutes?: true
  intervalHours?: true
  windowStartMinutes?: true
  windowEndMinutes?: true
  days?: true
  monthlyDaysBeforeEnd?: true
  retryAttempts?: true
}

export type SyncScheduleMinAggregateInputType = {
  userId?: true
  enabled?: true
  mode?: true
  dailyAtMinutes?: true
  intervalHours?: true
  windowStartMinutes?: true
  windowEndMinutes?: true
  monthlyDaysBeforeEnd?: true
  monthlyWeekdaysOnly?: true
  targetUrl?: true
  retryAttempts?: true
  skipEmptyDays?: true
  updatedAt?: true
}

export type SyncScheduleMaxAggregateInputType = {
  userId?: true
  enabled?: true
  mode?: true
  dailyAtMinutes?: true
  intervalHours?: true
  windowStartMinutes?: true
  windowEndMinutes?: true
  monthlyDaysBeforeEnd?: true
  monthlyWeekdaysOnly?: true
  targetUrl?: true
  retryAttempts?: true
  skipEmptyDays?: true
  updatedAt?: true
}

export type SyncScheduleCountAggregateInputType = {
  userId?: true
  enabled?: true
  mode?: true
  dailyAtMinutes?: true
  intervalHours?: true
  windowStartMinutes?: true
  windowEndMinutes?: true
  days?: true
  monthlyDaysBeforeEnd?: true
  monthlyWeekdaysOnly?: true
  targetUrl?: true
  retryAttempts?: true
  skipEmptyDays?: true
  updatedAt?: true
  _all?: true
}

export type SyncScheduleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SyncSchedule to aggregate.
   */
  where?: Prisma.SyncScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncSchedules to fetch.
   */
  orderBy?: Prisma.SyncScheduleOrderByWithRelationInput | Prisma.SyncScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SyncScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SyncSchedules
  **/
  _count?: true | SyncScheduleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SyncScheduleAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SyncScheduleSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SyncScheduleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SyncScheduleMaxAggregateInputType
}

export type GetSyncScheduleAggregateType<T extends SyncScheduleAggregateArgs> = {
      [P in keyof T & keyof AggregateSyncSchedule]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSyncSchedule[P]>
    : Prisma.GetScalarType<T[P], AggregateSyncSchedule[P]>
}




export type SyncScheduleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SyncScheduleWhereInput
  orderBy?: Prisma.SyncScheduleOrderByWithAggregationInput | Prisma.SyncScheduleOrderByWithAggregationInput[]
  by: Prisma.SyncScheduleScalarFieldEnum[] | Prisma.SyncScheduleScalarFieldEnum
  having?: Prisma.SyncScheduleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SyncScheduleCountAggregateInputType | true
  _avg?: SyncScheduleAvgAggregateInputType
  _sum?: SyncScheduleSumAggregateInputType
  _min?: SyncScheduleMinAggregateInputType
  _max?: SyncScheduleMaxAggregateInputType
}

export type SyncScheduleGroupByOutputType = {
  userId: string
  enabled: boolean
  mode: string
  dailyAtMinutes: number
  intervalHours: number
  windowStartMinutes: number
  windowEndMinutes: number
  days: number[]
  monthlyDaysBeforeEnd: number
  monthlyWeekdaysOnly: boolean
  targetUrl: string
  retryAttempts: number
  skipEmptyDays: boolean
  updatedAt: Date
  _count: SyncScheduleCountAggregateOutputType | null
  _avg: SyncScheduleAvgAggregateOutputType | null
  _sum: SyncScheduleSumAggregateOutputType | null
  _min: SyncScheduleMinAggregateOutputType | null
  _max: SyncScheduleMaxAggregateOutputType | null
}

export type GetSyncScheduleGroupByPayload<T extends SyncScheduleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SyncScheduleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SyncScheduleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SyncScheduleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SyncScheduleGroupByOutputType[P]>
      }
    >
  >



export type SyncScheduleWhereInput = {
  AND?: Prisma.SyncScheduleWhereInput | Prisma.SyncScheduleWhereInput[]
  OR?: Prisma.SyncScheduleWhereInput[]
  NOT?: Prisma.SyncScheduleWhereInput | Prisma.SyncScheduleWhereInput[]
  userId?: Prisma.StringFilter<"SyncSchedule"> | string
  enabled?: Prisma.BoolFilter<"SyncSchedule"> | boolean
  mode?: Prisma.StringFilter<"SyncSchedule"> | string
  dailyAtMinutes?: Prisma.IntFilter<"SyncSchedule"> | number
  intervalHours?: Prisma.IntFilter<"SyncSchedule"> | number
  windowStartMinutes?: Prisma.IntFilter<"SyncSchedule"> | number
  windowEndMinutes?: Prisma.IntFilter<"SyncSchedule"> | number
  days?: Prisma.IntNullableListFilter<"SyncSchedule">
  monthlyDaysBeforeEnd?: Prisma.IntFilter<"SyncSchedule"> | number
  monthlyWeekdaysOnly?: Prisma.BoolFilter<"SyncSchedule"> | boolean
  targetUrl?: Prisma.StringFilter<"SyncSchedule"> | string
  retryAttempts?: Prisma.IntFilter<"SyncSchedule"> | number
  skipEmptyDays?: Prisma.BoolFilter<"SyncSchedule"> | boolean
  updatedAt?: Prisma.DateTimeFilter<"SyncSchedule"> | Date | string
}

export type SyncScheduleOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  dailyAtMinutes?: Prisma.SortOrder
  intervalHours?: Prisma.SortOrder
  windowStartMinutes?: Prisma.SortOrder
  windowEndMinutes?: Prisma.SortOrder
  days?: Prisma.SortOrder
  monthlyDaysBeforeEnd?: Prisma.SortOrder
  monthlyWeekdaysOnly?: Prisma.SortOrder
  targetUrl?: Prisma.SortOrder
  retryAttempts?: Prisma.SortOrder
  skipEmptyDays?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SyncScheduleWhereUniqueInput = Prisma.AtLeast<{
  userId?: string
  AND?: Prisma.SyncScheduleWhereInput | Prisma.SyncScheduleWhereInput[]
  OR?: Prisma.SyncScheduleWhereInput[]
  NOT?: Prisma.SyncScheduleWhereInput | Prisma.SyncScheduleWhereInput[]
  enabled?: Prisma.BoolFilter<"SyncSchedule"> | boolean
  mode?: Prisma.StringFilter<"SyncSchedule"> | string
  dailyAtMinutes?: Prisma.IntFilter<"SyncSchedule"> | number
  intervalHours?: Prisma.IntFilter<"SyncSchedule"> | number
  windowStartMinutes?: Prisma.IntFilter<"SyncSchedule"> | number
  windowEndMinutes?: Prisma.IntFilter<"SyncSchedule"> | number
  days?: Prisma.IntNullableListFilter<"SyncSchedule">
  monthlyDaysBeforeEnd?: Prisma.IntFilter<"SyncSchedule"> | number
  monthlyWeekdaysOnly?: Prisma.BoolFilter<"SyncSchedule"> | boolean
  targetUrl?: Prisma.StringFilter<"SyncSchedule"> | string
  retryAttempts?: Prisma.IntFilter<"SyncSchedule"> | number
  skipEmptyDays?: Prisma.BoolFilter<"SyncSchedule"> | boolean
  updatedAt?: Prisma.DateTimeFilter<"SyncSchedule"> | Date | string
}, "userId">

export type SyncScheduleOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  dailyAtMinutes?: Prisma.SortOrder
  intervalHours?: Prisma.SortOrder
  windowStartMinutes?: Prisma.SortOrder
  windowEndMinutes?: Prisma.SortOrder
  days?: Prisma.SortOrder
  monthlyDaysBeforeEnd?: Prisma.SortOrder
  monthlyWeekdaysOnly?: Prisma.SortOrder
  targetUrl?: Prisma.SortOrder
  retryAttempts?: Prisma.SortOrder
  skipEmptyDays?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SyncScheduleCountOrderByAggregateInput
  _avg?: Prisma.SyncScheduleAvgOrderByAggregateInput
  _max?: Prisma.SyncScheduleMaxOrderByAggregateInput
  _min?: Prisma.SyncScheduleMinOrderByAggregateInput
  _sum?: Prisma.SyncScheduleSumOrderByAggregateInput
}

export type SyncScheduleScalarWhereWithAggregatesInput = {
  AND?: Prisma.SyncScheduleScalarWhereWithAggregatesInput | Prisma.SyncScheduleScalarWhereWithAggregatesInput[]
  OR?: Prisma.SyncScheduleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SyncScheduleScalarWhereWithAggregatesInput | Prisma.SyncScheduleScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"SyncSchedule"> | string
  enabled?: Prisma.BoolWithAggregatesFilter<"SyncSchedule"> | boolean
  mode?: Prisma.StringWithAggregatesFilter<"SyncSchedule"> | string
  dailyAtMinutes?: Prisma.IntWithAggregatesFilter<"SyncSchedule"> | number
  intervalHours?: Prisma.IntWithAggregatesFilter<"SyncSchedule"> | number
  windowStartMinutes?: Prisma.IntWithAggregatesFilter<"SyncSchedule"> | number
  windowEndMinutes?: Prisma.IntWithAggregatesFilter<"SyncSchedule"> | number
  days?: Prisma.IntNullableListFilter<"SyncSchedule">
  monthlyDaysBeforeEnd?: Prisma.IntWithAggregatesFilter<"SyncSchedule"> | number
  monthlyWeekdaysOnly?: Prisma.BoolWithAggregatesFilter<"SyncSchedule"> | boolean
  targetUrl?: Prisma.StringWithAggregatesFilter<"SyncSchedule"> | string
  retryAttempts?: Prisma.IntWithAggregatesFilter<"SyncSchedule"> | number
  skipEmptyDays?: Prisma.BoolWithAggregatesFilter<"SyncSchedule"> | boolean
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SyncSchedule"> | Date | string
}

export type SyncScheduleCreateInput = {
  userId: string
  enabled?: boolean
  mode?: string
  dailyAtMinutes?: number
  intervalHours?: number
  windowStartMinutes?: number
  windowEndMinutes?: number
  days?: Prisma.SyncScheduleCreatedaysInput | number[]
  monthlyDaysBeforeEnd?: number
  monthlyWeekdaysOnly?: boolean
  targetUrl?: string
  retryAttempts?: number
  skipEmptyDays?: boolean
  updatedAt?: Date | string
}

export type SyncScheduleUncheckedCreateInput = {
  userId: string
  enabled?: boolean
  mode?: string
  dailyAtMinutes?: number
  intervalHours?: number
  windowStartMinutes?: number
  windowEndMinutes?: number
  days?: Prisma.SyncScheduleCreatedaysInput | number[]
  monthlyDaysBeforeEnd?: number
  monthlyWeekdaysOnly?: boolean
  targetUrl?: string
  retryAttempts?: number
  skipEmptyDays?: boolean
  updatedAt?: Date | string
}

export type SyncScheduleUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  dailyAtMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  intervalHours?: Prisma.IntFieldUpdateOperationsInput | number
  windowStartMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  windowEndMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  days?: Prisma.SyncScheduleUpdatedaysInput | number[]
  monthlyDaysBeforeEnd?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyWeekdaysOnly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  targetUrl?: Prisma.StringFieldUpdateOperationsInput | string
  retryAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  skipEmptyDays?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncScheduleUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  dailyAtMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  intervalHours?: Prisma.IntFieldUpdateOperationsInput | number
  windowStartMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  windowEndMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  days?: Prisma.SyncScheduleUpdatedaysInput | number[]
  monthlyDaysBeforeEnd?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyWeekdaysOnly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  targetUrl?: Prisma.StringFieldUpdateOperationsInput | string
  retryAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  skipEmptyDays?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncScheduleCreateManyInput = {
  userId: string
  enabled?: boolean
  mode?: string
  dailyAtMinutes?: number
  intervalHours?: number
  windowStartMinutes?: number
  windowEndMinutes?: number
  days?: Prisma.SyncScheduleCreatedaysInput | number[]
  monthlyDaysBeforeEnd?: number
  monthlyWeekdaysOnly?: boolean
  targetUrl?: string
  retryAttempts?: number
  skipEmptyDays?: boolean
  updatedAt?: Date | string
}

export type SyncScheduleUpdateManyMutationInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  dailyAtMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  intervalHours?: Prisma.IntFieldUpdateOperationsInput | number
  windowStartMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  windowEndMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  days?: Prisma.SyncScheduleUpdatedaysInput | number[]
  monthlyDaysBeforeEnd?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyWeekdaysOnly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  targetUrl?: Prisma.StringFieldUpdateOperationsInput | string
  retryAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  skipEmptyDays?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncScheduleUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  dailyAtMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  intervalHours?: Prisma.IntFieldUpdateOperationsInput | number
  windowStartMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  windowEndMinutes?: Prisma.IntFieldUpdateOperationsInput | number
  days?: Prisma.SyncScheduleUpdatedaysInput | number[]
  monthlyDaysBeforeEnd?: Prisma.IntFieldUpdateOperationsInput | number
  monthlyWeekdaysOnly?: Prisma.BoolFieldUpdateOperationsInput | boolean
  targetUrl?: Prisma.StringFieldUpdateOperationsInput | string
  retryAttempts?: Prisma.IntFieldUpdateOperationsInput | number
  skipEmptyDays?: Prisma.BoolFieldUpdateOperationsInput | boolean
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IntNullableListFilter<$PrismaModel = never> = {
  equals?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  has?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  hasEvery?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  hasSome?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type SyncScheduleCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  dailyAtMinutes?: Prisma.SortOrder
  intervalHours?: Prisma.SortOrder
  windowStartMinutes?: Prisma.SortOrder
  windowEndMinutes?: Prisma.SortOrder
  days?: Prisma.SortOrder
  monthlyDaysBeforeEnd?: Prisma.SortOrder
  monthlyWeekdaysOnly?: Prisma.SortOrder
  targetUrl?: Prisma.SortOrder
  retryAttempts?: Prisma.SortOrder
  skipEmptyDays?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SyncScheduleAvgOrderByAggregateInput = {
  dailyAtMinutes?: Prisma.SortOrder
  intervalHours?: Prisma.SortOrder
  windowStartMinutes?: Prisma.SortOrder
  windowEndMinutes?: Prisma.SortOrder
  days?: Prisma.SortOrder
  monthlyDaysBeforeEnd?: Prisma.SortOrder
  retryAttempts?: Prisma.SortOrder
}

export type SyncScheduleMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  dailyAtMinutes?: Prisma.SortOrder
  intervalHours?: Prisma.SortOrder
  windowStartMinutes?: Prisma.SortOrder
  windowEndMinutes?: Prisma.SortOrder
  monthlyDaysBeforeEnd?: Prisma.SortOrder
  monthlyWeekdaysOnly?: Prisma.SortOrder
  targetUrl?: Prisma.SortOrder
  retryAttempts?: Prisma.SortOrder
  skipEmptyDays?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SyncScheduleMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  dailyAtMinutes?: Prisma.SortOrder
  intervalHours?: Prisma.SortOrder
  windowStartMinutes?: Prisma.SortOrder
  windowEndMinutes?: Prisma.SortOrder
  monthlyDaysBeforeEnd?: Prisma.SortOrder
  monthlyWeekdaysOnly?: Prisma.SortOrder
  targetUrl?: Prisma.SortOrder
  retryAttempts?: Prisma.SortOrder
  skipEmptyDays?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SyncScheduleSumOrderByAggregateInput = {
  dailyAtMinutes?: Prisma.SortOrder
  intervalHours?: Prisma.SortOrder
  windowStartMinutes?: Prisma.SortOrder
  windowEndMinutes?: Prisma.SortOrder
  days?: Prisma.SortOrder
  monthlyDaysBeforeEnd?: Prisma.SortOrder
  retryAttempts?: Prisma.SortOrder
}

export type SyncScheduleCreatedaysInput = {
  set: number[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type SyncScheduleUpdatedaysInput = {
  set?: number[]
  push?: number | number[]
}



export type SyncScheduleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  enabled?: boolean
  mode?: boolean
  dailyAtMinutes?: boolean
  intervalHours?: boolean
  windowStartMinutes?: boolean
  windowEndMinutes?: boolean
  days?: boolean
  monthlyDaysBeforeEnd?: boolean
  monthlyWeekdaysOnly?: boolean
  targetUrl?: boolean
  retryAttempts?: boolean
  skipEmptyDays?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["syncSchedule"]>

export type SyncScheduleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  enabled?: boolean
  mode?: boolean
  dailyAtMinutes?: boolean
  intervalHours?: boolean
  windowStartMinutes?: boolean
  windowEndMinutes?: boolean
  days?: boolean
  monthlyDaysBeforeEnd?: boolean
  monthlyWeekdaysOnly?: boolean
  targetUrl?: boolean
  retryAttempts?: boolean
  skipEmptyDays?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["syncSchedule"]>

export type SyncScheduleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  enabled?: boolean
  mode?: boolean
  dailyAtMinutes?: boolean
  intervalHours?: boolean
  windowStartMinutes?: boolean
  windowEndMinutes?: boolean
  days?: boolean
  monthlyDaysBeforeEnd?: boolean
  monthlyWeekdaysOnly?: boolean
  targetUrl?: boolean
  retryAttempts?: boolean
  skipEmptyDays?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["syncSchedule"]>

export type SyncScheduleSelectScalar = {
  userId?: boolean
  enabled?: boolean
  mode?: boolean
  dailyAtMinutes?: boolean
  intervalHours?: boolean
  windowStartMinutes?: boolean
  windowEndMinutes?: boolean
  days?: boolean
  monthlyDaysBeforeEnd?: boolean
  monthlyWeekdaysOnly?: boolean
  targetUrl?: boolean
  retryAttempts?: boolean
  skipEmptyDays?: boolean
  updatedAt?: boolean
}

export type SyncScheduleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "enabled" | "mode" | "dailyAtMinutes" | "intervalHours" | "windowStartMinutes" | "windowEndMinutes" | "days" | "monthlyDaysBeforeEnd" | "monthlyWeekdaysOnly" | "targetUrl" | "retryAttempts" | "skipEmptyDays" | "updatedAt", ExtArgs["result"]["syncSchedule"]>

export type $SyncSchedulePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SyncSchedule"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    enabled: boolean
    /**
     * 'daily' | 'interval' | 'monthly' | 'manual'
     */
    mode: string
    dailyAtMinutes: number
    intervalHours: number
    windowStartMinutes: number
    windowEndMinutes: number
    /**
     * Date#getDay() numbering, 0 = Sunday.
     */
    days: number[]
    monthlyDaysBeforeEnd: number
    monthlyWeekdaysOnly: boolean
    targetUrl: string
    retryAttempts: number
    skipEmptyDays: boolean
    updatedAt: Date
  }, ExtArgs["result"]["syncSchedule"]>
  composites: {}
}

export type SyncScheduleGetPayload<S extends boolean | null | undefined | SyncScheduleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload, S>

export type SyncScheduleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SyncScheduleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SyncScheduleCountAggregateInputType | true
  }

export interface SyncScheduleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SyncSchedule'], meta: { name: 'SyncSchedule' } }
  /**
   * Find zero or one SyncSchedule that matches the filter.
   * @param {SyncScheduleFindUniqueArgs} args - Arguments to find a SyncSchedule
   * @example
   * // Get one SyncSchedule
   * const syncSchedule = await prisma.syncSchedule.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SyncScheduleFindUniqueArgs>(args: Prisma.SelectSubset<T, SyncScheduleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SyncScheduleClient<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SyncSchedule that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SyncScheduleFindUniqueOrThrowArgs} args - Arguments to find a SyncSchedule
   * @example
   * // Get one SyncSchedule
   * const syncSchedule = await prisma.syncSchedule.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SyncScheduleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SyncScheduleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SyncScheduleClient<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SyncSchedule that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncScheduleFindFirstArgs} args - Arguments to find a SyncSchedule
   * @example
   * // Get one SyncSchedule
   * const syncSchedule = await prisma.syncSchedule.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SyncScheduleFindFirstArgs>(args?: Prisma.SelectSubset<T, SyncScheduleFindFirstArgs<ExtArgs>>): Prisma.Prisma__SyncScheduleClient<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SyncSchedule that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncScheduleFindFirstOrThrowArgs} args - Arguments to find a SyncSchedule
   * @example
   * // Get one SyncSchedule
   * const syncSchedule = await prisma.syncSchedule.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SyncScheduleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SyncScheduleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SyncScheduleClient<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SyncSchedules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncScheduleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SyncSchedules
   * const syncSchedules = await prisma.syncSchedule.findMany()
   * 
   * // Get first 10 SyncSchedules
   * const syncSchedules = await prisma.syncSchedule.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const syncScheduleWithUserIdOnly = await prisma.syncSchedule.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends SyncScheduleFindManyArgs>(args?: Prisma.SelectSubset<T, SyncScheduleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SyncSchedule.
   * @param {SyncScheduleCreateArgs} args - Arguments to create a SyncSchedule.
   * @example
   * // Create one SyncSchedule
   * const SyncSchedule = await prisma.syncSchedule.create({
   *   data: {
   *     // ... data to create a SyncSchedule
   *   }
   * })
   * 
   */
  create<T extends SyncScheduleCreateArgs>(args: Prisma.SelectSubset<T, SyncScheduleCreateArgs<ExtArgs>>): Prisma.Prisma__SyncScheduleClient<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SyncSchedules.
   * @param {SyncScheduleCreateManyArgs} args - Arguments to create many SyncSchedules.
   * @example
   * // Create many SyncSchedules
   * const syncSchedule = await prisma.syncSchedule.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SyncScheduleCreateManyArgs>(args?: Prisma.SelectSubset<T, SyncScheduleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SyncSchedules and returns the data saved in the database.
   * @param {SyncScheduleCreateManyAndReturnArgs} args - Arguments to create many SyncSchedules.
   * @example
   * // Create many SyncSchedules
   * const syncSchedule = await prisma.syncSchedule.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SyncSchedules and only return the `userId`
   * const syncScheduleWithUserIdOnly = await prisma.syncSchedule.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SyncScheduleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SyncScheduleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SyncSchedule.
   * @param {SyncScheduleDeleteArgs} args - Arguments to delete one SyncSchedule.
   * @example
   * // Delete one SyncSchedule
   * const SyncSchedule = await prisma.syncSchedule.delete({
   *   where: {
   *     // ... filter to delete one SyncSchedule
   *   }
   * })
   * 
   */
  delete<T extends SyncScheduleDeleteArgs>(args: Prisma.SelectSubset<T, SyncScheduleDeleteArgs<ExtArgs>>): Prisma.Prisma__SyncScheduleClient<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SyncSchedule.
   * @param {SyncScheduleUpdateArgs} args - Arguments to update one SyncSchedule.
   * @example
   * // Update one SyncSchedule
   * const syncSchedule = await prisma.syncSchedule.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SyncScheduleUpdateArgs>(args: Prisma.SelectSubset<T, SyncScheduleUpdateArgs<ExtArgs>>): Prisma.Prisma__SyncScheduleClient<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SyncSchedules.
   * @param {SyncScheduleDeleteManyArgs} args - Arguments to filter SyncSchedules to delete.
   * @example
   * // Delete a few SyncSchedules
   * const { count } = await prisma.syncSchedule.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SyncScheduleDeleteManyArgs>(args?: Prisma.SelectSubset<T, SyncScheduleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SyncSchedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncScheduleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SyncSchedules
   * const syncSchedule = await prisma.syncSchedule.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SyncScheduleUpdateManyArgs>(args: Prisma.SelectSubset<T, SyncScheduleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SyncSchedules and returns the data updated in the database.
   * @param {SyncScheduleUpdateManyAndReturnArgs} args - Arguments to update many SyncSchedules.
   * @example
   * // Update many SyncSchedules
   * const syncSchedule = await prisma.syncSchedule.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SyncSchedules and only return the `userId`
   * const syncScheduleWithUserIdOnly = await prisma.syncSchedule.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SyncScheduleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SyncScheduleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SyncSchedule.
   * @param {SyncScheduleUpsertArgs} args - Arguments to update or create a SyncSchedule.
   * @example
   * // Update or create a SyncSchedule
   * const syncSchedule = await prisma.syncSchedule.upsert({
   *   create: {
   *     // ... data to create a SyncSchedule
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SyncSchedule we want to update
   *   }
   * })
   */
  upsert<T extends SyncScheduleUpsertArgs>(args: Prisma.SelectSubset<T, SyncScheduleUpsertArgs<ExtArgs>>): Prisma.Prisma__SyncScheduleClient<runtime.Types.Result.GetResult<Prisma.$SyncSchedulePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SyncSchedules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncScheduleCountArgs} args - Arguments to filter SyncSchedules to count.
   * @example
   * // Count the number of SyncSchedules
   * const count = await prisma.syncSchedule.count({
   *   where: {
   *     // ... the filter for the SyncSchedules we want to count
   *   }
   * })
  **/
  count<T extends SyncScheduleCountArgs>(
    args?: Prisma.Subset<T, SyncScheduleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SyncScheduleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SyncSchedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncScheduleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SyncScheduleAggregateArgs>(args: Prisma.Subset<T, SyncScheduleAggregateArgs>): Prisma.PrismaPromise<GetSyncScheduleAggregateType<T>>

  /**
   * Group by SyncSchedule.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncScheduleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SyncScheduleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SyncScheduleGroupByArgs['orderBy'] }
      : { orderBy?: SyncScheduleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SyncScheduleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSyncScheduleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SyncSchedule model
 */
readonly fields: SyncScheduleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SyncSchedule.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SyncScheduleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SyncSchedule model
 */
export interface SyncScheduleFieldRefs {
  readonly userId: Prisma.FieldRef<"SyncSchedule", 'String'>
  readonly enabled: Prisma.FieldRef<"SyncSchedule", 'Boolean'>
  readonly mode: Prisma.FieldRef<"SyncSchedule", 'String'>
  readonly dailyAtMinutes: Prisma.FieldRef<"SyncSchedule", 'Int'>
  readonly intervalHours: Prisma.FieldRef<"SyncSchedule", 'Int'>
  readonly windowStartMinutes: Prisma.FieldRef<"SyncSchedule", 'Int'>
  readonly windowEndMinutes: Prisma.FieldRef<"SyncSchedule", 'Int'>
  readonly days: Prisma.FieldRef<"SyncSchedule", 'Int[]'>
  readonly monthlyDaysBeforeEnd: Prisma.FieldRef<"SyncSchedule", 'Int'>
  readonly monthlyWeekdaysOnly: Prisma.FieldRef<"SyncSchedule", 'Boolean'>
  readonly targetUrl: Prisma.FieldRef<"SyncSchedule", 'String'>
  readonly retryAttempts: Prisma.FieldRef<"SyncSchedule", 'Int'>
  readonly skipEmptyDays: Prisma.FieldRef<"SyncSchedule", 'Boolean'>
  readonly updatedAt: Prisma.FieldRef<"SyncSchedule", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SyncSchedule findUnique
 */
export type SyncScheduleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * Filter, which SyncSchedule to fetch.
   */
  where: Prisma.SyncScheduleWhereUniqueInput
}

/**
 * SyncSchedule findUniqueOrThrow
 */
export type SyncScheduleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * Filter, which SyncSchedule to fetch.
   */
  where: Prisma.SyncScheduleWhereUniqueInput
}

/**
 * SyncSchedule findFirst
 */
export type SyncScheduleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * Filter, which SyncSchedule to fetch.
   */
  where?: Prisma.SyncScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncSchedules to fetch.
   */
  orderBy?: Prisma.SyncScheduleOrderByWithRelationInput | Prisma.SyncScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SyncSchedules.
   */
  cursor?: Prisma.SyncScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncSchedules.
   */
  distinct?: Prisma.SyncScheduleScalarFieldEnum | Prisma.SyncScheduleScalarFieldEnum[]
}

/**
 * SyncSchedule findFirstOrThrow
 */
export type SyncScheduleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * Filter, which SyncSchedule to fetch.
   */
  where?: Prisma.SyncScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncSchedules to fetch.
   */
  orderBy?: Prisma.SyncScheduleOrderByWithRelationInput | Prisma.SyncScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SyncSchedules.
   */
  cursor?: Prisma.SyncScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncSchedules.
   */
  distinct?: Prisma.SyncScheduleScalarFieldEnum | Prisma.SyncScheduleScalarFieldEnum[]
}

/**
 * SyncSchedule findMany
 */
export type SyncScheduleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * Filter, which SyncSchedules to fetch.
   */
  where?: Prisma.SyncScheduleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncSchedules to fetch.
   */
  orderBy?: Prisma.SyncScheduleOrderByWithRelationInput | Prisma.SyncScheduleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SyncSchedules.
   */
  cursor?: Prisma.SyncScheduleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncSchedules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncSchedules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncSchedules.
   */
  distinct?: Prisma.SyncScheduleScalarFieldEnum | Prisma.SyncScheduleScalarFieldEnum[]
}

/**
 * SyncSchedule create
 */
export type SyncScheduleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * The data needed to create a SyncSchedule.
   */
  data: Prisma.XOR<Prisma.SyncScheduleCreateInput, Prisma.SyncScheduleUncheckedCreateInput>
}

/**
 * SyncSchedule createMany
 */
export type SyncScheduleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SyncSchedules.
   */
  data: Prisma.SyncScheduleCreateManyInput | Prisma.SyncScheduleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SyncSchedule createManyAndReturn
 */
export type SyncScheduleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * The data used to create many SyncSchedules.
   */
  data: Prisma.SyncScheduleCreateManyInput | Prisma.SyncScheduleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SyncSchedule update
 */
export type SyncScheduleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * The data needed to update a SyncSchedule.
   */
  data: Prisma.XOR<Prisma.SyncScheduleUpdateInput, Prisma.SyncScheduleUncheckedUpdateInput>
  /**
   * Choose, which SyncSchedule to update.
   */
  where: Prisma.SyncScheduleWhereUniqueInput
}

/**
 * SyncSchedule updateMany
 */
export type SyncScheduleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SyncSchedules.
   */
  data: Prisma.XOR<Prisma.SyncScheduleUpdateManyMutationInput, Prisma.SyncScheduleUncheckedUpdateManyInput>
  /**
   * Filter which SyncSchedules to update
   */
  where?: Prisma.SyncScheduleWhereInput
  /**
   * Limit how many SyncSchedules to update.
   */
  limit?: number
}

/**
 * SyncSchedule updateManyAndReturn
 */
export type SyncScheduleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * The data used to update SyncSchedules.
   */
  data: Prisma.XOR<Prisma.SyncScheduleUpdateManyMutationInput, Prisma.SyncScheduleUncheckedUpdateManyInput>
  /**
   * Filter which SyncSchedules to update
   */
  where?: Prisma.SyncScheduleWhereInput
  /**
   * Limit how many SyncSchedules to update.
   */
  limit?: number
}

/**
 * SyncSchedule upsert
 */
export type SyncScheduleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * The filter to search for the SyncSchedule to update in case it exists.
   */
  where: Prisma.SyncScheduleWhereUniqueInput
  /**
   * In case the SyncSchedule found by the `where` argument doesn't exist, create a new SyncSchedule with this data.
   */
  create: Prisma.XOR<Prisma.SyncScheduleCreateInput, Prisma.SyncScheduleUncheckedCreateInput>
  /**
   * In case the SyncSchedule was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SyncScheduleUpdateInput, Prisma.SyncScheduleUncheckedUpdateInput>
}

/**
 * SyncSchedule delete
 */
export type SyncScheduleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
  /**
   * Filter which SyncSchedule to delete.
   */
  where: Prisma.SyncScheduleWhereUniqueInput
}

/**
 * SyncSchedule deleteMany
 */
export type SyncScheduleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SyncSchedules to delete
   */
  where?: Prisma.SyncScheduleWhereInput
  /**
   * Limit how many SyncSchedules to delete.
   */
  limit?: number
}

/**
 * SyncSchedule without action
 */
export type SyncScheduleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncSchedule
   */
  select?: Prisma.SyncScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncSchedule
   */
  omit?: Prisma.SyncScheduleOmit<ExtArgs> | null
}
